FROM golang:1.22 AS builder
WORKDIR /go/src/github.com/k8snetworkplumbingwg/sriov-network-operator
COPY . .
RUN make _build-sriov-network-config-daemon BIN_PATH=build/_output/cmd

FROM quay.io/centos/centos:stream9
ARG MSTFLINT=mstflint
# We have to ensure that pciutils is installed. This package is needed for mstfwreset to succeed.
# xref pkg/vendors/mellanox/mellanox.go#L150
RUN ARCH_DEP_PKGS=$(if [ "$(uname -m)" != "s390x" ]; then echo -n ${MSTFLINT} ; fi) && yum -y install hwdata pciutils $ARCH_DEP_PKGS && yum clean all
# Monkeypatch mstconfig to retry on exit code 3 (transient errors)
COPY hack/mstconfig-wrapper.sh /usr/bin/mstconfig.fake
RUN if [ -f /usr/bin/mstconfig ]; then \
    chmod +x /usr/bin/mstconfig.fake && \
    mv /usr/bin/mstconfig /usr/bin/mstconfig.real && \
    mv /usr/bin/mstconfig.fake /usr/bin/mstconfig; \
else rm -f /usr/bin/mstconfig.fake; fi
LABEL io.k8s.display-name="sriov-network-config-daemon" \
      io.k8s.description="This is a daemon that manage and config sriov network devices in Kubernetes cluster"
COPY --from=builder /go/src/github.com/k8snetworkplumbingwg/sriov-network-operator/build/_output/cmd/sriov-network-config-daemon /usr/bin/
COPY bindata /bindata
CMD ["/usr/bin/sriov-network-config-daemon"]
