apiVersion: sriovnetwork.openshift.io/v1
kind: SriovIBNetwork
metadata:
  name: sriovibnetwork-sample
spec:
  networkNamespace: default
  resourceName: ib_network
  capabilities: '{"infinibandGUID": true}'
  pKey: "0x0040"
  linkState: enable
  ibKubernetesEnabled: true
